### ISSUE TITLE
Using yelp in node, sample idea

### ISSUE THREAD

**Issue by Junicus** [Agnostics/nightlife-app-react#1]
So after some unsuccessful searches I gave up and though of a different way to do it.  You could create a new endpoint in node for a get request, and forward the params to the yelp request like so

```
app.get('/testyelp', function(req, res) {

  yelp.search({
      term: 'food',
      location: 'Montreal',
    })
    .then((data) => {
      console.log(data);
      res.json(data);
    })
    .catch((err) => {
      console.error(err);
    });
})
```

that was on your server.js, and have the click handler point to that new endpoint.  I'm guessing that the issue is that you are webpacking a module that probably is designed for using with node and not the browser, when you do that the browser is the one doing the call not node.  Result is that you get the access control thing, because it's the browser.

You were configuring cors and the headers in node, I noticed that the header never got set on the browser call.

hope that helps

**Comment by Astrobinary** [comment]
I can't believe I didn't try this at first. It works flawlessly and as intended. Lesson learned, thanks again @Junicus !
